apiVersion: apps/v1
kind: Deployment
metadata:
  name: tofomvc
  labels:
    app: tofomvc
spec:
  selector:
    matchLabels:
      app: tofomvc
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: tofomvc
        tier: frontend
    spec:
      containers:
      - name: tofomvc
        image: 127.0.0.1:5000/tofomvc:1.1.BUILD_NUMBER-prod
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: tofomvc
  labels:
    app: tofomvc
spec:
  ports:
  - port: 3000
  selector:
    app: tofomvc
    tier: frontend
  type: NodePort