apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pipeline-k8s
spec:
  selector:
    matchLabels:
      app: pipeline-k8s
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: pipeline-k8s
    spec:
      containers:
      - name: pipeline-k8s
        image: 127.0.0.1:5000/pipeline-k8s:$BUILD_NUMBER
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-k8s
  labels:
    app: pipeline-k8s
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: pipeline-k8s