- hosts: localhost
  gather_facts: false
  tasks:
  - name: Deploy the application
    k8s:
      state: present
      validate_certs: no
      namespace: default
      definition: "{{ lookup('file', 'deployment.yaml') | from_yaml }}"